server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.1:8848
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: test
        uri: lb://cloud-auth
        predicates:
          - Path=/auth
      - id: payment_routh                       #路由的ID，没有固定规则但要求唯一，简易配合服务名
        uri: lb://nacos-payment-provider        # 路由指向目的地URL或服务名，客户端请求最终被转发到的微服务
        predicates:                             #路由条件
          - Path=/provider/**                     #断言，路径相匹配的进行路由
      - id: consumer
        uri: lb://nacos-consumer
        predicates:
          - Path=/consumer/**          #断言，路径相匹配的进行路由
