server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
        server-addr: 39.106.52.109:8848 #配置Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
        uri: lb://nacos-payment-provider
        predicates:                    #路由条件
        - Path=/provider/**          #断言，路径相匹配的进行路由
      - id: consumer
        uri: lb://nacos-consumer
        predicates:
        - Path=/consumer/**          #断言，路径相匹配的进行路由
