spring:
  profiles:
    active: dev
  cloud:
#    sentinel:
#      transport:
#        # sentinel dashboard 地址
##        dashboard: 39.106.52.109:8858
#        dashboard: localhost:8080
#        # 默认为8719，如果被占用会自动+1，直到找到为止
#        port: 8719
#      #      # 流控规则持久化到nacos
#      datasource:
#        dsl:
#          nacos:
##            server-addr: 39.106.52.109:8848
#            server-addr: localhost:8848
#            data-id: ${spring.application.name}
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

