server:
  port: 83

spring:
  application:
    name: nacos-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.52.109:3307/springcloud?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://39.106.52.109:3307/springcloud?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: 39.106.52.109
    port: 9080
    timeout: 1000
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 39.106.52.109:8848
    sentinel:
      transport:
        # sentinel dashboard 地址
        dashboard: 39.106.52.109:8858
#        dashboard: localhost:8080
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
      #      # 流控规则持久化到nacos
      datasource:
        dsl:
          nacos:
            server-addr: 39.106.52.109:8848
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

##########mybatis配置##########
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zhao.springcloud.module.*.entity       #所有Entity别名类所在包

management:
  endpoints:
    web:
      exposure:
        include: "*"