server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
#        server-addr: 39.106.52.109:8848 #配置Nacos地址
  kafka:
    bootstrap-servers: 39.106.52.109:9092
    producer:
      # 每次批量发送消息的数量
      batch-size: 16
      # 缓存容量
      buffer-memory: 33554432
      #设置大于0的值，则客户端会将发送失败的记录重新发送
      retries: 0
      # 指定消息key和消息体的编解码方式 UTF-8
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false
kafka:
  #订阅的主题
  topic: topic-test-01
  #主题消费分组
  group: group-test-01
management:
  endpoints:
    web:
      exposure:
        include: '*'  #监控

